### ISSUE TITLE
Unknown status packet

### ISSUE THREAD

**Issue by Thoky81** [mattsaxon/HASS-Jablotron80#9]
I am getting lots of these errors: **Unknown status packet is b'\x82\x02=\xff\x00\x00\x00\x00'** Always with different numbers. Do you have any idea?

**Comment by Thoky81** [comment]
Unknown status packet is b'\x82\x02=\xff\x00\x00\x00\x00'
7:43 PM custom_components/jablotron/alarm_control_panel.py (WARNING) - message first occured at 8:21 AM and shows up 7255 times

**Comment by mattsaxon** [comment]
That won't have an impact on performance, I've just been trying to remove all the unknown packets.

Latest version has this specific one fixed, so please use that.

However it does mean that you now have a version that support entering of the code, issue #5, does that work as you'd expect?

**Comment by Thoky81** [comment]
Thanks for reply. I have uploaded your last code but still getting the errors. Sorry but didn’t have time to check the codes issue #5 😀 with your new version. But I will do soon. I have also updated the your code today afternoon but still getting the same errors. 
Unknown status packet is b'\x82\x01=\x00\x00\x00\x00\x00

**Comment by Thoky81** [comment]
Sure no performance issues but it’s annoying 😀

**Comment by mattsaxon** [comment]
are you sure you got the latest code?

I made the commit which solved this particular one just yesterday, here the commit https://github.com/mattsaxon/HASS-Jablotron80/commit/af2371aea24fc3ecbac125c61d83bd7522c22801

I've made one further since then too, which removes another error.

**Comment by Thoky81** [comment]
I have uploaded your lates files today afternoon, but still seen this:

Unknown status packet is b'\x82\x01)\x00\x00\x00\x00\x00'
Unknown status packet is b'\x82\x01I\x00\x00\x00\x00\x00'
Unknown status packet is b'\x82\x01>\x00\x00\x00\x00\x00'
Unknown status packet is b'\x82\x01\r\x00\x00\x00\x00\x00'

**Comment by mattsaxon** [comment]
Fixed latest set of unknowns. Please try latest code.

**Comment by Thoky81** [comment]
Sorry for posting on closed issue but I am still getting the same logs:
Unknown status packet is b'\x82\x01\x04\x00\x00\x00\x00\x00

I have uploaded your lates files so I don’t know where is the problem.

Thanks

**Comment by mattsaxon** [comment]
No worries, we will fix these issues 1 by 1

**Comment by mattsaxon** [comment]
Updated with latest code to fix. Please reopen with additional errors.

**Comment by Thoky81** [comment]
I am still getting another one:
Unknown status packet is b'\x82\x01I\x00\x00\x00\x00\x00'

**Comment by mattsaxon** [comment]
Fixed in last commit

**Comment by filip-van-hoeckel** [comment]
Having heaps of those as well. How to solve?

**Comment by mattsaxon** [comment]
Well the unknown status packets themselves are not much of an issue (apart from filling up the log). Looking at your issues on HA community, however, the issue is that you are not getting an ‘known’ status packets, hence your alarm status is unknown.

As a quick scan it looked like you were only getting one type of packet, which suggests either there is a problem with your setup or your alarm behaves differently from any we’ve seen so far.

is your hardware on my supported list? I don’t recall and can’t check right now.

**Comment by filip-van-hoeckel** [comment]
JA-82K alarm with JA-82T cable. Looks to me like it's supported? Same cable and Jablotron 80 series central unit.

**Comment by mattsaxon** [comment]
Can you put your alarm in a set of different states, set, unset and setting and ready the status message from the logs. Seems your setup has different codes in use for me and others.

Once you have the ‘unknown’ message for each state post it here.

**Comment by mattsaxon** [comment]
So for example you logs has things like Unknown status packet is b'\x82\x01`\x00\x00\x00\x00\x00'

This is likely to be different when you alarm is in different states, so if you can tell me the specific debug for each state I can fix this.
